site:
  title: Web Data Integration
  url: https://webdataintegration.info/
  start_page: wdi::index.adoc
content:
  sources:
  - url: https://github.com/mjgp2/wdi
    branches: master
    start_path: articles
ui:
  bundle:
    url: https://github.com/mjgp2/antora-theme/releases/download/0.1/ui-bundle.zip?v=1
    snapshot: true
output:
  dir: ./docs